language: php

php:
    - 5.3
    - 5.4

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev

script: bin/phpunit --configuration ./build/travis-ci.xml

notifications:
    email: false
    irc:
        channels:
            - "irc.freenode.org#phpunit"
    use_notice: true

matrix:
    fast_finish: true
